name: Notify

on: [push, pull_request, workflow_dispatch]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Notifying
        uses: davoudarsalani/action-notify@master
        with:
          telegram_message: |
            ${{ github.event_name }}
            ${{ github.repository_owner }}
            ${{ github.repository }}
            Commit message: ${{ github.event.commits[0].message }}
            https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
